package chisquare;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import static javax.management.Query.value;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    private ArrayList<Double> list = new ArrayList<>();
    private ArrayList<Double> storeData = new ArrayList<>();
    private double[] d = new double[10000];
    private double value;

    public Home() {

        initComponents();

    }

    public ArrayList<Double> getResult() {

        // your code goes here
        //observed chi square
        //significant chi square
        for (int i = 0; i < d.length - 1; i++) {

            double observed = Double.parseDouble(jobservedValue.getText().toString());  //expected data. Here expected data for all ovserved data is same
            double expected = Double.parseDouble(jexpectedValue.getText().toString());

            d[i] = Math.pow(observed - expected, 2) / expected;

             
            value = d[i];
            
           

        }
        

        value += value;
        System.out.println(value);

        list.add(this.value);
        return this.list;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jobservedValue = new javax.swing.JTextField();
        jexpectedValue = new javax.swing.JTextField();
        jsubmitBtn = new javax.swing.JButton();
        jcalculateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jchiSquare = new javax.swing.JTextField();
        jsignificant = new javax.swing.JTextField();
        jclear = new javax.swing.JButton();
        jcheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Chi Square Calculator");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Observed Value :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 80, 110, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Expected value:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 140, 100, 15);

        jobservedValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jobservedValueKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jobservedValueKeyTyped(evt);
            }
        });
        jPanel1.add(jobservedValue);
        jobservedValue.setBounds(460, 80, 180, 30);

        jexpectedValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jexpectedValueKeyTyped(evt);
            }
        });
        jPanel1.add(jexpectedValue);
        jexpectedValue.setBounds(460, 140, 180, 30);

        jsubmitBtn.setBackground(new java.awt.Color(102, 102, 102));
        jsubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jsubmitBtn.setText("Submit");
        jsubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jsubmitBtn);
        jsubmitBtn.setBounds(460, 210, 110, 23);

        jcalculateBtn.setBackground(new java.awt.Color(102, 102, 102));
        jcalculateBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcalculateBtn.setText("Calculate");
        jcalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalculateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jcalculateBtn);
        jcalculateBtn.setBounds(220, 210, 100, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Chi Square [1-alpha , k-1]:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 370, 170, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Chi Square:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 320, 90, 15);
        jPanel1.add(jchiSquare);
        jchiSquare.setBounds(460, 300, 170, 30);

        jsignificant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsignificantActionPerformed(evt);
            }
        });
        jsignificant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jsignificantKeyTyped(evt);
            }
        });
        jPanel1.add(jsignificant);
        jsignificant.setBounds(460, 370, 170, 30);

        jclear.setBackground(new java.awt.Color(204, 0, 51));
        jclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jclear.setText("Clear");
        jclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearActionPerformed(evt);
            }
        });
        jPanel1.add(jclear);
        jclear.setBounds(210, 450, 100, 23);

        jcheck.setBackground(new java.awt.Color(0, 102, 102));
        jcheck.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcheck.setText("Check");
        jcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckActionPerformed(evt);
            }
        });
        jPanel1.add(jcheck);
        jcheck.setBounds(460, 450, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsignificantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsignificantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsignificantActionPerformed

    private void jcalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalculateBtnActionPerformed

        for (int i = 0; i < this.storeData.size(); i++) {
            jchiSquare.setText(String.valueOf(this.storeData.get(i)));
          

        }


    }//GEN-LAST:event_jcalculateBtnActionPerformed

    private void jsubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitBtnActionPerformed
        if (jobservedValue.getText().toString().isEmpty() || jexpectedValue.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Please Complete Your input!");

        } else {

            this.storeData = getResult();
            jobservedValue.setText("");
            jexpectedValue.setText("");
        }
    }//GEN-LAST:event_jsubmitBtnActionPerformed

    private void jclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearActionPerformed
        jobservedValue.setText("");
        jexpectedValue.setText("");
        jchiSquare.setText("");
        jsignificant.setText("");
    }//GEN-LAST:event_jclearActionPerformed

    private void jcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckActionPerformed

        if (jsignificant.getText().toString().isEmpty() || jchiSquare.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Your Check Value!");
        } else {
            double calculateResult = Double.parseDouble(jchiSquare.getText().toString());
            double compareResult = Double.parseDouble(jsignificant.getText().toString());
            if (calculateResult < compareResult) {
                JOptionPane.showMessageDialog(null, " Accepted!");

            } else if (calculateResult > compareResult) {
                JOptionPane.showMessageDialog(null, " Rejected!");

            }
        }

    }//GEN-LAST:event_jcheckActionPerformed

    private void jobservedValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobservedValueKeyPressed

    }//GEN-LAST:event_jobservedValueKeyPressed

    private void jobservedValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobservedValueKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();

        }
    }//GEN-LAST:event_jobservedValueKeyTyped

    private void jexpectedValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jexpectedValueKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();

        }
    }//GEN-LAST:event_jexpectedValueKeyTyped

    private void jsignificantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsignificantKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();

        }
    }//GEN-LAST:event_jsignificantKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jcalculateBtn;
    private javax.swing.JButton jcheck;
    private javax.swing.JTextField jchiSquare;
    private javax.swing.JButton jclear;
    private javax.swing.JTextField jexpectedValue;
    private javax.swing.JTextField jobservedValue;
    private javax.swing.JTextField jsignificant;
    private javax.swing.JButton jsubmitBtn;
    // End of variables declaration//GEN-END:variables
}
